// Curated IB study resources, organised by programme and subject.
// Each resource has: title, url, type ('video'|'notes'|'practice'|'tools'|'official')

export const RESOURCES = {
  MYP: [
    {
      id: 'myp-english',
      name: 'English',
      icon: '📖',
      colour: '#6366f1',
      resources: [
        { title: 'IB MYP English – Official Subject Brief', url: 'https://www.ibo.org/programmes/middle-years-programme/curriculum/language-and-literature/', type: 'official' },
        { title: 'CommonLit – Free literary texts & comprehension', url: 'https://www.commonlit.org/', type: 'notes' },
        { title: 'Purdue OWL – Writing & grammar guides', url: 'https://owl.purdue.edu/owl/general_writing/index.html', type: 'notes' },
        { title: 'LitCharts – Literary analysis & summaries', url: 'https://www.litcharts.com/', type: 'notes' },
        { title: 'Khan Academy – Grammar essentials', url: 'https://www.khanacademy.org/humanities/grammar', type: 'practice' },
        { title: 'BBC Bitesize – English Language skills', url: 'https://www.bbc.co.uk/bitesize/subjects/zr9d7ty', type: 'notes' },
      ],
    },
    {
      id: 'myp-ins',
      name: 'Individuals & Societies (InS)',
      icon: '🌍',
      colour: '#f59e0b',
      resources: [
        { title: 'IB MYP Individuals & Societies – Official Brief', url: 'https://www.ibo.org/programmes/middle-years-programme/curriculum/individuals-and-societies/', type: 'official' },
        { title: 'Khan Academy – World History', url: 'https://www.khanacademy.org/humanities/world-history', type: 'notes' },
        { title: 'Khan Academy – US History & Geography', url: 'https://www.khanacademy.org/humanities/us-history', type: 'notes' },
        { title: 'BBC Bitesize – Geography', url: 'https://www.bbc.co.uk/bitesize/subjects/zng4d2p', type: 'notes' },
        { title: 'Crash Course – History & Geography (YouTube)', url: 'https://www.youtube.com/@crashcourse', type: 'video' },
        { title: 'Britannica – Reference & research', url: 'https://www.britannica.com/', type: 'notes' },
      ],
    },
    {
      id: 'myp-chemistry',
      name: 'Chemistry',
      icon: '⚗️',
      colour: '#06b6d4',
      resources: [
        { title: 'IB MYP Sciences – Official Subject Brief', url: 'https://www.ibo.org/programmes/middle-years-programme/curriculum/sciences/', type: 'official' },
        { title: 'Khan Academy – Chemistry', url: 'https://www.khanacademy.org/science/chemistry', type: 'practice' },
        { title: 'BBC Bitesize – Chemistry', url: 'https://www.bbc.co.uk/bitesize/subjects/znxtyrd', type: 'notes' },
        { title: 'Tyler DeWitt – Chemistry YouTube channel', url: 'https://www.youtube.com/@tylerdewitt', type: 'video' },
        { title: 'ChemLibreTexts – Free chemistry textbooks', url: 'https://chem.libretexts.org/', type: 'notes' },
        { title: 'Royal Society of Chemistry – Education resources', url: 'https://edu.rsc.org/', type: 'notes' },
      ],
    },
    {
      id: 'myp-biology',
      name: 'Biology',
      icon: '🧬',
      colour: '#22c55e',
      resources: [
        { title: 'IB MYP Sciences – Official Subject Brief', url: 'https://www.ibo.org/programmes/middle-years-programme/curriculum/sciences/', type: 'official' },
        { title: 'Khan Academy – Biology', url: 'https://www.khanacademy.org/science/biology', type: 'practice' },
        { title: 'BBC Bitesize – Biology', url: 'https://www.bbc.co.uk/bitesize/subjects/z9ddmp3', type: 'notes' },
        { title: 'Amoeba Sisters – Biology YouTube channel', url: 'https://www.youtube.com/@AmoebaSisters', type: 'video' },
        { title: 'BioNinja – MYP/DP Biology notes', url: 'https://ib.bioninja.com.au/', type: 'notes' },
        { title: 'Biology LibreTexts – Free biology textbooks', url: 'https://bio.libretexts.org/', type: 'notes' },
      ],
    },
  ],

  DP: [
    {
      id: 'dp-chemistry',
      name: 'Chemistry',
      icon: '⚗️',
      colour: '#06b6d4',
      resources: [
        { title: 'IB Chemistry – Official Subject Guide (IBO)', url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/sciences/chemistry/', type: 'official' },
        { title: 'MSJChem – Complete IB Chemistry notes & videos', url: 'https://www.msjchem.com/', type: 'notes' },
        { title: 'Richard Thornley – IB Chemistry YouTube', url: 'https://www.youtube.com/@RichardThornleyIB', type: 'video' },
        { title: 'Chemrev.net – IB Chemistry revision', url: 'https://www.chemrevise.org/', type: 'notes' },
        { title: 'ChemLibreTexts – Free chemistry reference', url: 'https://chem.libretexts.org/', type: 'notes' },
        { title: 'IBDocuments – Past papers & markschemes', url: 'https://www.ibdocuments.com/', type: 'practice' },
      ],
    },
    {
      id: 'dp-economics',
      name: 'Economics',
      icon: '📈',
      colour: '#8b5cf6',
      resources: [
        { title: 'IB Economics – Official Subject Guide (IBO)', url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/individuals-and-societies/economics/', type: 'official' },
        { title: 'Brad Cartwright – IB Economics YouTube', url: 'https://www.youtube.com/@bradcartwrighteconomics', type: 'video' },
        { title: 'IB Economics – Comprehensive revision notes', url: 'https://www.ibeconomics.com/', type: 'notes' },
        { title: 'EconplusDal – IB/A-Level Economics YouTube', url: 'https://www.youtube.com/@EconplusDal', type: 'video' },
        { title: 'Khan Academy – Macroeconomics', url: 'https://www.khanacademy.org/economics-finance-domain/macroeconomics', type: 'practice' },
        { title: 'IBDocuments – Past papers & markschemes', url: 'https://www.ibdocuments.com/', type: 'practice' },
      ],
    },
    {
      id: 'dp-ess',
      name: 'ESS',
      icon: '🌿',
      colour: '#10b981',
      resources: [
        { title: 'IB ESS – Official Subject Guide (IBO)', url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/sciences/environmental-systems-and-societies/', type: 'official' },
        { title: 'John Crane – ESS textbook & resources', url: 'https://www.ess-textbook.com/', type: 'notes' },
        { title: 'I Am ESS – YouTube revision channel', url: 'https://www.youtube.com/@IAMESS', type: 'video' },
        { title: 'ESS IA & EE guide – Lanterna Education', url: 'https://www.lanternaeducation.com/ib/ess/', type: 'notes' },
        { title: 'IBDocuments – Past papers & markschemes', url: 'https://www.ibdocuments.com/', type: 'practice' },
        { title: 'Our World in Data – Environmental statistics', url: 'https://ourworldindata.org/', type: 'tools' },
      ],
    },
    {
      id: 'dp-biology',
      name: 'Biology',
      icon: '🧬',
      colour: '#22c55e',
      resources: [
        { title: 'IB Biology – Official Subject Guide (IBO)', url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/sciences/biology/', type: 'official' },
        { title: 'BioNinja – Complete IB Biology notes', url: 'https://ib.bioninja.com.au/', type: 'notes' },
        { title: 'Richard Thornley – IB Biology YouTube', url: 'https://www.youtube.com/@RichardThornleyIB', type: 'video' },
        { title: 'Biology Online – Reference & terminology', url: 'https://www.biologyonline.com/', type: 'notes' },
        { title: 'Khan Academy – AP/IB Biology', url: 'https://www.khanacademy.org/science/ap-biology', type: 'practice' },
        { title: 'IBDocuments – Past papers & markschemes', url: 'https://www.ibdocuments.com/', type: 'practice' },
      ],
    },
    {
      id: 'dp-business',
      name: 'Business Management',
      icon: '💼',
      colour: '#f97316',
      resources: [
        { title: 'IB Business Management – Official Subject Guide', url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/individuals-and-societies/business-management/', type: 'official' },
        { title: 'BusinessManagementIB – YouTube channel', url: 'https://www.youtube.com/@BusinessManagementIB', type: 'video' },
        { title: 'IB Business Management – Revision notes (Quizlet)', url: 'https://quizlet.com/subject/ib-business-management/', type: 'practice' },
        { title: 'Tutor2u – Business concepts & theory', url: 'https://www.tutor2u.net/business', type: 'notes' },
        { title: 'Khan Academy – Finance & capital markets', url: 'https://www.khanacademy.org/economics-finance-domain/core-finance', type: 'practice' },
        { title: 'IBDocuments – Past papers & markschemes', url: 'https://www.ibdocuments.com/', type: 'practice' },
      ],
    },
    {
      id: 'dp-physics',
      name: 'Physics',
      icon: '⚛️',
      colour: '#3b82f6',
      resources: [
        { title: 'IB Physics – Official Subject Guide (IBO)', url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/sciences/physics/', type: 'official' },
        { title: 'Physics with Mr. Mackenzie – IB notes & videos', url: 'https://physicswithmrmackenzie.com/', type: 'notes' },
        { title: 'Richard Thornley – IB Physics YouTube', url: 'https://www.youtube.com/@RichardThornleyIB', type: 'video' },
        { title: 'Khan Academy – AP Physics', url: 'https://www.khanacademy.org/science/ap-physics-1', type: 'practice' },
        { title: 'PhET Simulations – Interactive physics', url: 'https://phet.colorado.edu/', type: 'tools' },
        { title: 'IBDocuments – Past papers & markschemes', url: 'https://www.ibdocuments.com/', type: 'practice' },
      ],
    },
    {
      id: 'dp-sehs',
      name: 'Sports, Exercise & Health Science',
      icon: '🏃',
      colour: '#ec4899',
      resources: [
        { title: 'IB SEHS – Official Subject Guide (IBO)', url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/sciences/sports-exercise-and-health-science/', type: 'official' },
        { title: 'IB SEHS Notes – Revision Village', url: 'https://revisionvillage.com/ib-sehs/', type: 'notes' },
        { title: 'Khan Academy – Health & medicine', url: 'https://www.khanacademy.org/science/health-and-medicine', type: 'practice' },
        { title: 'Crash Course – Biology & human anatomy (YouTube)', url: 'https://www.youtube.com/@crashcourse', type: 'video' },
        { title: 'IBDocuments – Past papers & markschemes', url: 'https://www.ibdocuments.com/', type: 'practice' },
        { title: 'Human Kinetics – Sport science resources', url: 'https://humankinetics.me/', type: 'notes' },
      ],
    },
    {
      id: 'dp-eng-lang-lit',
      name: 'English A: Language & Literature',
      icon: '✍️',
      colour: '#6366f1',
      resources: [
        { title: 'IB English A – Official Subject Guide (IBO)', url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/language-and-literature/language-a-language-and-literature/', type: 'official' },
        { title: 'LitCharts – Literary analysis & summaries', url: 'https://www.litcharts.com/', type: 'notes' },
        { title: 'Shmoop – Literature & language analysis', url: 'https://www.shmoop.com/', type: 'notes' },
        { title: 'Revision Village – IB English resources', url: 'https://revisionvillage.com/ib-english/', type: 'notes' },
        { title: 'IBDocuments – Past papers & markschemes', url: 'https://www.ibdocuments.com/', type: 'practice' },
        { title: 'Purdue OWL – Academic writing & citations', url: 'https://owl.purdue.edu/', type: 'tools' },
      ],
    },
    {
      id: 'dp-eng-lit',
      name: 'English A: Literature',
      icon: '📚',
      colour: '#a78bfa',
      resources: [
        { title: 'IB English A – Official Subject Guide (IBO)', url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/language-and-literature/language-a-literature/', type: 'official' },
        { title: 'LitCharts – Literary analysis & summaries', url: 'https://www.litcharts.com/', type: 'notes' },
        { title: 'SparkNotes – Literature study guides', url: 'https://www.sparknotes.com/', type: 'notes' },
        { title: 'Revision Village – IB English resources', url: 'https://revisionvillage.com/ib-english/', type: 'notes' },
        { title: 'IBDocuments – Past papers & markschemes', url: 'https://www.ibdocuments.com/', type: 'practice' },
        { title: 'Purdue OWL – Academic writing & citations', url: 'https://owl.purdue.edu/', type: 'tools' },
      ],
    },
  ],
};

export const TYPE_LABELS = {
  official: { label: 'Official', colour: 'text-yellow-400 bg-yellow-400/10 border-yellow-400/30' },
  notes:    { label: 'Notes',    colour: 'text-blue-400 bg-blue-400/10 border-blue-400/30' },
  video:    { label: 'Video',    colour: 'text-red-400 bg-red-400/10 border-red-400/30' },
  practice: { label: 'Practice', colour: 'text-green-400 bg-green-400/10 border-green-400/30' },
  tools:    { label: 'Tools',    colour: 'text-purple-400 bg-purple-400/10 border-purple-400/30' },
};
